export const apiUrl = process.env.NODE_ENV !== 'production' ? 'http://localhost:4000/api' : 'url';

export const LOCAL_STORAGE_TOKEN_NAME = 'learnit-token';
export const DEPARTMENTS_LOADED_SUCCESS = 'DEPARTMENTS_LOADED_SUCCESS';
export const ROOMS_LOADED_SUCCESS = 'ROOMS_LOADED_SUCCESS';
export const INPATIENTS_LOADED_SUCCESS = 'INPATIENTS_LOADED_SUCCESS';
export const INPATIENTS_LOADED_FAIL = 'INPATIETS_LOADED_FAIL';
export const INPATIENT_FIND = 'INPATIENT_FIND';
export const COUPONCARES_LOADED_SUCCESS = 'COUPONCARES_LOADED_SUCCESS';
export const COUPONCARES_LOADED_FAIL = 'COUPONCARES_LOADED_FAIL';
